### PR TITLE
WIP: Dalamud Launcher

### PR DESCRIPTION
**Pull request by fitzchivalrik**
It is hot WIP, but I wanted to have it more in the open, especially for discussing style, API surface etc.
Because of the recent merge which changed the folder structure I just created
a new branch and commit instead of rebasing and merging it all.

I first tried to port `DalamudLauncher` straight from the C# XL source, but I did not feel like it maps that great, and I struggled quite a bit. I am certain this was mainly due to me being not knowledgeable enough, however, I decided to
start from scratch with the `DalamudUpdater` this time.

I try to keep in mind what the crate should provide - downloading and starting dalamud - and not just follow the C# source code.
Furthermore, I try to minimise outside interactions and exposed API, this can lead to a different API surface, but I think it's inevitable that patterns will change.

A primary TODO right now is to figure out how to correctly create absolute paths from `std::path::Path`, `canonicalize()` seemed not to do what I expected.

One of the biggest missing things is general 'launch programs (addons)' support and how the launching of dalamud fits into that.
Also, it is unclear as of now how status changes are propagated back to the GUI overlay.
Instead of solving it all at once, I thought it more sensible to refactor later after more and more stuff becomes concrete.

I currently try to work with async, as src-tauri uses tokio. I tried to avoid a specific runtime dependency, but it seems to be needed for some features, e.g. async sleep and async IO.

Using async might be not the best choice, however, and e.g. channels and threads more preferable. That remains to be seen.

### CODE REVIEW

**Comment by goaaats** [comment]
We should definitely port XL's addon system into the rust glue, will be easy to implement this as an addon then.

**Comment by fitzchivalrik** [comment]
Launching FFXIV on windows works, same as C#XL but with less error checks and not as ergonomic.
The ergonomics, checks and API are better done later I think though; that is also why it is WIP.
I also have no experience how one would want to do that natively in Linux/start FFXIV with wine or such.

A high-level test, launching FFXIV with DEV arguments and injecting Dalamud, is successful on Windows though.

Next, I will do the WIP of the Addon's system and hopefully with all three crates and a dummy 'Start' button in the GUI it will be easier to create an API around it.

**Comment by daemitus** [comment]
I used canonicalize from dunce, worked as expected.

**Comment by goaaats** [comment]
Looks great, I would honestly just move the stuff from the `ffxiv` crate into libxl, since you will have that anyway if you want to start xiv and we'll have less crates to work with.

**Comment by fitzchivalrik** [comment]
I think smaller, more specialised crates are better than one having it all - it makes one think more careful about what to expose as the public API, makes compilation times stay manageable and lets one re-use  functionality easier (e.g. the idea of a small shim (crate) inside wine which was brought up in the discord).  
I thought of `libxl` as the high-level orchestrion crate which combines the 'low-level' crates into a complete 'handle FFXIV' experience, which is then exposed to and consumed by tauri (or any other gui framework).
I would even propose to remove the types from `libxl` and put them in one crate and put e.g. `oauth` inside its own and make a crate for the steam integration too, such that no crate depends on `libxl`, just some common `types` crate, and `libxl` is the one depending on all and weaving it together.
It just feels like such clear separation is more beneficial in the long-run.

I might be completely off, though, and maybe it is more comfortable to put it in `libxl`. If you want me to do that, I of course can.

**Comment by daemitus** [comment]
So long as there are clear delineations between modules one lib should be
fine. More crates means more toml to update

**Pull request closed without merging**
